language: node_js
node_js:
  - "6.9"

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run tests

notifications:
  email:
    on_failure: change
    on_success: change
