sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11'

addons:

before_script:
- echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
- set -x && apt-get update && apt-get install -y xvfb google-chrome-stable
- ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome
- npm install -g @angular/cli gulp typescript ts-node typings
- npm install

script: npm run tests
